### ISSUE TITLE
Missing sudo in /etc/exports

### ISSUE THREAD

**Issue by PauloLaScience** [pgstef/pgstef.github.io#1]
Hi,
`[paul@secondary ~]$ sudo echo "/mnt/backups primary(rw,sync,no_root_squash)" >> /etc/exports
-bash: /etc/exports: Permission denied`

Kind regards
Paulem

**Comment by PauloLaScience** [comment]
I found this to solve:
`sudo sh -c 'echo "/mnt/backups primary(rw,sync,no_root_squash)" >> /etc/exports'`

**Comment by PauloLaScience** [comment]
same issue for fstab but also missing mount point. I have to create /mnt/backups to be able mount via NFS
Kind regards,
Paulem

**Comment by pgstef** [comment]
Improved in commit 20f9f059954f08f7c890c7ebf16bf856235ede95.

Thanks !
